### PR TITLE
Experimental solr 6 infrastructure

### PR DESCRIPTION
**Pull request by jnguyenx**
Added functional tests for Amigo and Monarch, with an embedded instance of solr.

Note that the bbop-response-golr dependency in package.json needs to be upgraded to the latest one (0.0.7 when available on npm), in order for the tests to compile.

### CODE REVIEW

**Comment by kltm** [comment]
dependency for bbop-response-golr should bump to 0.0.8 😞

**Comment by jnguyenx** [comment]
:white_check_mark:

**Comment by kltm** [comment]
Looking clear at my end. I'll merge with 0.0.11 and let the NPM release code bump it.

**Comment by kltm** [comment]
bbop-manager-golr@0.0.12

**Pull request merged**
